# Generated by Django 3.1.4 on 2021-01-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_clientapprovallog_deliverypersonapprovallog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientapprovallog',
            old_name='admin',
            new_name='approved_by',
        ),
    ]
