# Generated by Django 3.1.4 on 2021-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20201231_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_person/photos/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
