# Generated by Django 3.1.4 on 2021-01-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_auto_20210129_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientapprovallog',
            old_name='approved_by',
            new_name='action_by',
        ),
    ]
