# Generated by Django 3.1.4 on 2021-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_auto_20210104_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='raahim123', max_length=300),
            preserve_default=False,
        ),
    ]
