# Generated by Django 3.1.4 on 2021-01-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_auto_20210129_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientapprovallog',
            old_name='action_by',
            new_name='admin',
        ),
    ]
