# Generated by Django 3.1.4 on 2021-01-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_remove_adminuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
