require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# Override Firebase SDK Version
$FirebaseSDKVersion = '8.5.0'
# $RNFirebaseAsStaticFramework = true# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'
# or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
# for Analytics without IDFA collection capability

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


target 'orddel' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # pod 'Firebase/Analytics'
  # target 'ImageLockerMobileTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  #   end

  target 'orddelTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.5' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'orddel-tvOS' do
  # Pods for orddel-tvOS

  target 'orddel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end





