"""
Django settings for ordel project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3&6_2w!n-d*na4@a(p-us406+b4!6^xle2993x!^lefg_^*t&s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ec2-3-129-128-169.us-east-2.compute.amazonaws.com', '127.0.0.1', '192.168.1.99']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_rest_passwordreset',
    'django_crontab',

    # Django Apps
    'order',
    'payment',
    'products',
    'admin_dashboard',
    'client_app',
    'delivery_app',

    # REST_FRAMEWORK
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_tracking',
    'storages',
    'django_email_verification',
    'fcm_django',

    # Extensions
    'django_extensions',
    'django_seed',
    'axes',
    'reset_migrations',  # https://pypi.org/project/django-reset-migrations/
    'imagekit',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware'
]

CRONJOBS = [
    ('* * * * *', 'products.cron.update_avg_price_job', '>> /etc/orddel-crontab.log', {'verbose': 1})
]
CRONTAB_COMMAND_SUFFIX = '2>&1'

ROOT_URLCONF = 'ordel.urls'

EMAIL_TEMPLATE_PATH = os.path.join(BASE_DIR, 'mail_body.html')
EMAIL_SUCCESS_TEMPLATE = os.path.join(BASE_DIR, 'confirm_template.html')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ordel.wsgi.application'

# REST FRAMEWORK
REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    #
    # ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25
}

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAAEdSwBq8:APA91bG85e6LgqIu7vUsEmGyjwcv61AW7-d3jYDK5YjYkzzrvaLS8kUtvGeYdRS4uiB_4rEkZ77g4nhJcU3OJjfkZrN3dOPjF-PankIW2UVVI0jgnFavtGZpPA8dki2BrSBEOYKlGady"
}


AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    # 'axes.backends.AxesBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesBackend'
]
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'orddel',
        'USER': 'postgres',
        'PASSWORD': 'postgres123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=4),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


# Email configuration
EMAIL_ACTIVE_FIELD = 'is_active'
EMAIL_SERVER = 'smtp.gmail.com'
# EMAIL_SERVER = 'mail.viltco.com'
EMAIL_ADDRESS = 'leadarc123@gmail.com'
# EMAIL_ADDRESS = 'orddel@viltco.com'
EMAIL_FROM_ADDRESS = 'orddel@viltco.com'
EMAIL_PASSWORD = '9WiPy98qhUPBvFL' # os.environ['password_key'] suggested
# EMAIL_PASSWORD = 'orddel@3221'  # os.environ['password_key'] suggested
EMAIL_MAIL_SUBJECT = 'Confirm your email'
EMAIL_MAIL_HTML = EMAIL_TEMPLATE_PATH
# EMAIL_MAIL_PLAIN = 'mail_body.txt'
EMAIL_PAGE_TEMPLATE = EMAIL_SUCCESS_TEMPLATE
EMAIL_PAGE_DOMAIN = 'http://ec2-3-129-128-169.us-east-2.compute.amazonaws.com:8000'


# Reset password SMTP configuration
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'mail.viltco.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'orddel@viltco.com'
EMAIL_HOST_USER = 'leadarc123@gmail.com'
EMAIL_HOST_PASSWORD = '9WiPy98qhUPBvFL'
# EMAIL_HOST_PASSWORD = 'orddel@3221'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


STATIC_URL = os.path.join(BASE_DIR, 'static/')
STATIC_ROOT = STATIC_URL

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AWS_ACCESS_KEY_ID = 'AKIAYD4FFDBGKS2T7FSP'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'orddel-frontend'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_REGION_NAME = 'us-east-2'
AWS_S3_SIGNATURE_VERSION = 's3v4'

# Twilio Account
# TWILIO_ACCOUNT_SID = "AC8d6c1e71edeb9459705b7320568df7ca"
# TWILIO_AUTH_TOKEN = "4c992942b54cc4c0b88cf857cad5c200"
# SERVICE_SID = "VA98a469ee1743df522f3d0a89df50556c"
TWILIO_ACCOUNT_SID = "AC1bff27816a73d875efc57d1a54eaf7f1"
TWILIO_AUTH_TOKEN = "46049db1db0055d84ca56824c7a18b21"
SERVICE_SID = "VA7bf9da7b14d553e1e4f4bf0d77fb8bdc"

# Stripe API Keys Test
STRIPE_PUBLISHABLE_KEY = 'pk_test_51IVGKwDfezRTPDs34lUTyxAmb2chp2zcCZpEbMwV7NkZWRufIcMJj3EILXrCcYZtWRFFtn34s0cWy6dE4wkSAhiF00425cFai7'
STRIPE_SECRET_KEY = 'sk_test_51IVGKwDfezRTPDs3rwZEwqnKVGp6o9ehpuOIQyCJ5opnwQ6Bwi6O9HBVx2x48sTpjRkDZt4e2EPuSUrfKtfpLyKj00g1s0RcGH'

# CELERY STUFF
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'
