# Generated by Django 2.2.7 on 2021-04-29 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('buying_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount_shopped', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery_person/photos/')),
                ('no_of_invoices', models.IntegerField(default=0)),
                ('used_invoices', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('otp_status', models.BooleanField(default=False)),
                ('admin_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('unapproved', 'Unapproved'), ('cancelled', 'Cancelled')], max_length=300)),
                ('approval_read_status', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=True)),
                ('no_of_active_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('no_of_invoices', models.IntegerField(default=0)),
                ('validity_in_days', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=100)),
                ('license_image_front', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/')),
                ('license_image_back', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/')),
                ('copy_image_front', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/')),
                ('copy_image_back', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/')),
                ('license_no', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.DeliveryPerson')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonPackageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activated', models.DateField(auto_now=True)),
                ('date_expiry', models.DateField()),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], max_length=100)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.DeliveryPerson')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.DeliveryPersonPackage')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonBusinessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(null=True, upload_to='business/logo/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.DeliveryPerson')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_title', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_card_no', models.CharField(blank=True, max_length=150, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.DeliveryPerson')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.DeliveryPersonPackage'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
