# Generated by Django 3.1.5 on 2021-01-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('current_location', models.CharField(max_length=100)),
                ('no_of_orders', models.IntegerField(default=0)),
                ('buying_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount_shopped', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery_person/photos/<django.db.models.fields.related.ForeignKey>/')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=100)),
                ('license_image_front', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/<built-in function id>/')),
                ('license_image_back', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/<built-in function id>/')),
                ('copy_image_front', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/<built-in function id>/')),
                ('copy_image_back', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/<built-in function id>/')),
                ('license_no', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/<built-in function id>/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliveryperson')),
            ],
        ),
    ]
