# Generated by Django 3.1.4 on 2021-01-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPersonPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('no_of_invoices', models.IntegerField(default=10)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='otp_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consolidatedpurchase',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliveryperson'),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='admin_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('unapproved', 'Unapproved')], max_length=300),
        ),
        migrations.CreateModel(
            name='DeliveryPersonPackageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], max_length=100)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliveryperson')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliverypersonpackage')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonBusinessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(null=True, upload_to='business/logo/<django.db.models.fields.CharField>/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliveryperson')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_card_no', models.CharField(blank=True, max_length=150, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliveryperson')),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliverypersonpackage'),
        ),
    ]
