# Generated by Django 3.1.4 on 2021-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='no_of_orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
