# Generated by Django 3.1.4 on 2020-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
