# Generated by Django 3.1.4 on 2021-01-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='otp_status',
            field=models.BooleanField(default=False),
        ),
    ]
