# Generated by Django 3.1.4 on 2021-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_auto_20210128_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedpurchase',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
