# Generated by Django 3.1.4 on 2021-01-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_auto_20210122_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryperson',
            old_name='approval_status',
            new_name='admin_approval_status',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='email_status',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='otp_status',
        ),
    ]
