# Generated by Django 3.1.4 on 2020-12-31 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('delivery_app', '0002_auto_20201231_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='category',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='name',
            new_name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='logout',
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='year_registered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ConsolidatedPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost_per_unit', models.IntegerField()),
                ('purchased_from', models.CharField(max_length=300)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliveryperson')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
