# Generated by Django 3.1.4 on 2021-01-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('delivery_app', '0003_auto_20210124_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='no_of_invoices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.package'),
        ),
    ]
