# Generated by Django 3.1.4 on 2021-01-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_auto_20201231_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsolidatedPurchase',
        ),
    ]
