# Generated by Django 3.1.4 on 2021-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_consolidatedpurchase_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedpurchase',
            name='cost_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consolidatedpurchase',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='consolidatedpurchase',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
