# Generated by Django 3.1.4 on 2021-01-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_auto_20210104_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliveryperson'),
        ),
    ]
