# Generated by Django 3.1.4 on 2021-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0008_auto_20210104_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='password',
            field=models.CharField(default='raahim123', max_length=300),
            preserve_default=False,
        ),
    ]
