# Generated by Django 3.1.4 on 2021-01-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0009_deliveryperson_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_person/photos/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
