# Generated by Django 3.1.4 on 2021-01-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0010_auto_20210104_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='password',
        ),
    ]
