# Generated by Django 3.1.4 on 2021-01-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0011_remove_deliveryperson_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleRegistration',
            new_name='Vehicle',
        ),
    ]
