# Generated by Django 3.1.4 on 2021-01-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0014_auto_20210105_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='year_registered',
            new_name='date_created',
        ),
    ]
