# Generated by Django 3.1.4 on 2021-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0015_auto_20210105_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
