# Generated by Django 3.1.4 on 2021-01-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0016_auto_20210106_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
    ]
