# Generated by Django 3.1.4 on 2021-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0017_remove_vehicle_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
