# Generated by Django 3.1.4 on 2021-01-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0018_vehicle_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliveryperson'),
        ),
    ]
