# Generated by Django 3.1.5 on 2021-01-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('card_no', models.CharField(blank=True, max_length=150, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BusinessDetail',
            new_name='ClientBusinessDetail',
        ),
        migrations.RenameModel(
            old_name='Package',
            new_name='ClientPackage',
        ),
        migrations.RenameModel(
            old_name='ClientPackageLogs',
            new_name='ClientPackageLog',
        ),
        migrations.RenameModel(
            old_name='ShipmentAddress',
            new_name='ClientShipmentAddress',
        ),
        migrations.RemoveField(
            model_name='client',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email_status',
        ),
        migrations.AddField(
            model_name='client',
            name='admin_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('unapproved', 'Unapproved')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.AddField(
            model_name='clientbankdetail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.client'),
        ),
    ]
