# Generated by Django 3.1.4 on 2021-01-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='package',
        ),
    ]
