# Generated by Django 3.1.5 on 2021-01-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='no_of_invoices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='no_of_invoices',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ClientPackageLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.client')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.package')),
            ],
        ),
    ]
