# Generated by Django 3.1.4 on 2021-01-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='nature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
