# Generated by Django 3.1.4 on 2021-01-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_client_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
