# Generated by Django 3.1.4 on 2021-01-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_auto_20210107_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
