# Generated by Django 3.1.5 on 2021-01-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_auto_20210119_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='otp_status',
            field=models.BooleanField(default=False),
        ),
    ]
