# Generated by Django 3.1.4 on 2021-01-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_app', '0001_initial'),
        ('products', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=100)),
                ('order_title', models.CharField(blank=True, max_length=100, null=True)),
                ('order_created_datetime', models.DateTimeField(auto_now=True)),
                ('order_delivery_datetime', models.DateTimeField()),
                ('delivery_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('distance', models.CharField(blank=True, max_length=100, null=True)),
                ('total_units_ordered', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered')], max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash On Delivery'), ('online_payment', 'Online Payment')], max_length=100, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cart')),
                ('cart_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cartproducts')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliveryperson')),
                ('shipment_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.shipmentaddress')),
            ],
        ),
    ]
