# Generated by Django 3.1.5 on 2021-01-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsolidatedPurchase',
        ),
    ]
