# Generated by Django 3.1.4 on 2021-01-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='number_of_boxes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
