# Generated by Django 3.1.5 on 2021-01-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210115_0738'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddToCart',
            new_name='CartProducts',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_detail',
            new_name='cart_products',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cart'),
        ),
    ]
