# Generated by Django 3.1.5 on 2021-01-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('client_app', '0003_auto_20210113_1028'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='client',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='number_of_boxes',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='weight',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.client')),
            ],
        ),
        migrations.AddField(
            model_name='addtocart',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
    ]
