# Generated by Django 3.1.4 on 2021-01-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('delivery_app', '0004_delete_consolidatedpurchase'),
        ('order', '0002_auto_20210101_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost_per_unit', models.IntegerField()),
                ('purchased_from', models.CharField(max_length=300)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.deliveryperson')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
