# Generated by Django 3.1.5 on 2021-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_consolidatedpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='cart_products',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='cart_products',
            field=models.ManyToManyField(to='order.CartProducts'),
        ),
    ]
