# Generated by Django 3.1.5 on 2021-01-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210120_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='cart_products',
        ),
    ]
