# Generated by Django 3.1.5 on 2021-01-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderdetail_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='grand_total',
        ),
    ]
