# Generated by Django 3.1.5 on 2021-01-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
