# Generated by Django 3.1.5 on 2021-01-19 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('short_description', models.CharField(blank=True, max_length=800, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('unit', models.CharField(choices=[('dozen', 'Dozen'), ('weight', 'Weight'), ('no', 'No')], max_length=300)),
                ('avg_price', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('SIT', 'SIT'), ('TMT', 'TMT'), ('QAR', 'QAR'), ('XBD', 'XBD'), ('AFN', 'AFN'), ('JMD', 'JMD'), ('CVE', 'CVE'), ('LVR', 'LVR'), ('XUA', 'XUA'), ('YUM', 'YUM'), ('CDF', 'CDF'), ('TJS', 'TJS'), ('LTT', 'LTT'), ('CYP', 'CYP'), ('AOA', 'AOA'), ('XOF', 'XOF'), ('CAD', 'CAD'), ('MXV', 'MXV'), ('USS', 'USS'), ('MVP', 'MVP'), ('ZWD', 'ZWD'), ('ARS', 'ARS'), ('TPE', 'TPE'), ('DZD', 'DZD'), ('MDC', 'MDC'), ('SHP', 'SHP'), ('KES', 'KES'), ('KWD', 'KWD'), ('SYP', 'SYP'), ('LRD', 'LRD'), ('KRO', 'KRO'), ('SKK', 'SKK'), ('UGX', 'UGX'), ('IDR', 'IDR'), ('KZT', 'KZT'), ('LKR', 'LKR'), ('ISJ', 'ISJ'), ('NAD', 'NAD'), ('UYU', 'UYU'), ('DOP', 'DOP'), ('LTL', 'LTL'), ('MXN', 'MXN'), ('MGA', 'MGA'), ('FIM', 'FIM'), ('NGN', 'NGN'), ('ATS', 'ATS'), ('BEL', 'BEL'), ('XEU', 'XEU'), ('XAU', 'XAU'), ('YUD', 'YUD'), ('SAR', 'SAR'), ('TRL', 'TRL'), ('MGF', 'MGF'), ('PLZ', 'PLZ'), ('GNS', 'GNS'), ('ARP', 'ARP'), ('GHC', 'GHC'), ('ESB', 'ESB'), ('BEC', 'BEC'), ('DJF', 'DJF'), ('MAD', 'MAD'), ('LUC', 'LUC'), ('PHP', 'PHP'), ('BUK', 'BUK'), ('NIC', 'NIC'), ('LBP', 'LBP'), ('BAD', 'BAD'), ('BRL', 'BRL'), ('GIP', 'GIP'), ('VEF', 'VEF'), ('KHR', 'KHR'), ('BBD', 'BBD'), ('YDD', 'YDD'), ('BAN', 'BAN'), ('VND', 'VND'), ('NLG', 'NLG'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('WST', 'WST'), ('GBP', 'GBP'), ('ARA', 'ARA'), ('GWE', 'GWE'), ('TRY', 'TRY'), ('RWF', 'RWF'), ('XTS', 'XTS'), ('XAF', 'XAF'), ('ALK', 'ALK'), ('TTD', 'TTD'), ('BEF', 'BEF'), ('GYD', 'GYD'), ('UYW', 'UYW'), ('AFA', 'AFA'), ('HNL', 'HNL'), ('OMR', 'OMR'), ('CHF', 'CHF'), ('GWP', 'GWP'), ('ZMW', 'ZMW'), ('XAG', 'XAG'), ('BRN', 'BRN'), ('UGS', 'UGS'), ('UZS', 'UZS'), ('SZL', 'SZL'), ('CNY', 'CNY'), ('MMK', 'MMK'), ('EGP', 'EGP'), ('ESP', 'ESP'), ('MCF', 'MCF'), ('AUD', 'AUD'), ('STN', 'STN'), ('ERN', 'ERN'), ('CRC', 'CRC'), ('PGK', 'PGK'), ('MRU', 'MRU'), ('NOK', 'NOK'), ('XBA', 'XBA'), ('KRW', 'KRW'), ('CHE', 'CHE'), ('XPT', 'XPT'), ('IRR', 'IRR'), ('FRF', 'FRF'), ('BMD', 'BMD'), ('BOL', 'BOL'), ('ETB', 'ETB'), ('TND', 'TND'), ('CSK', 'CSK'), ('LSL', 'LSL'), ('MKD', 'MKD'), ('ALL', 'ALL'), ('ZAR', 'ZAR'), ('UAH', 'UAH'), ('MRO', 'MRO'), ('BGL', 'BGL'), ('LAK', 'LAK'), ('BGM', 'BGM'), ('ILP', 'ILP'), ('UYI', 'UYI'), ('ECV', 'ECV'), ('MAF', 'MAF'), ('RSD', 'RSD'), ('AZN', 'AZN'), ('RUR', 'RUR'), ('MZN', 'MZN'), ('XBB', 'XBB'), ('USN', 'USN'), ('GRD', 'GRD'), ('CNH', 'CNH'), ('TMM', 'TMM'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('PKR', 'PKR'), ('SEK', 'SEK'), ('BRR', 'BRR'), ('YUN', 'YUN'), ('AON', 'AON'), ('XFO', 'XFO'), ('YER', 'YER'), ('PLN', 'PLN'), ('AMD', 'AMD'), ('LYD', 'LYD'), ('LUL', 'LUL'), ('MDL', 'MDL'), ('NIO', 'NIO'), ('CSD', 'CSD'), ('MTP', 'MTP'), ('MYR', 'MYR'), ('DEM', 'DEM'), ('ZWL', 'ZWL'), ('SUR', 'SUR'), ('BZD', 'BZD'), ('KGS', 'KGS'), ('ZRZ', 'ZRZ'), ('INR', 'INR'), ('BYR', 'BYR'), ('CLP', 'CLP'), ('SRG', 'SRG'), ('NPR', 'NPR'), ('EEK', 'EEK'), ('AOR', 'AOR'), ('BOV', 'BOV'), ('AED', 'AED'), ('BRB', 'BRB'), ('ZWR', 'ZWR'), ('ISK', 'ISK'), ('BOP', 'BOP'), ('SVC', 'SVC'), ('SDP', 'SDP'), ('PEI', 'PEI'), ('BTN', 'BTN'), ('BWP', 'BWP'), ('MTL', 'MTL'), ('CLF', 'CLF'), ('CUC', 'CUC'), ('PAB', 'PAB'), ('VUV', 'VUV'), ('KRH', 'KRH'), ('MUR', 'MUR'), ('ECS', 'ECS'), ('MVR', 'MVR'), ('RHD', 'RHD'), ('UYP', 'UYP'), ('BGO', 'BGO'), ('KYD', 'KYD'), ('ZRN', 'ZRN'), ('VES', 'VES'), ('BDT', 'BDT'), ('GQE', 'GQE'), ('THB', 'THB'), ('MXP', 'MXP'), ('AOK', 'AOK'), ('ILS', 'ILS'), ('COP', 'COP'), ('GTQ', 'GTQ'), ('SLL', 'SLL'), ('BAM', 'BAM'), ('MWK', 'MWK'), ('MNT', 'MNT'), ('LUF', 'LUF'), ('ILR', 'ILR'), ('XFU', 'XFU'), ('AWG', 'AWG'), ('KPW', 'KPW'), ('ANG', 'ANG'), ('XDR', 'XDR'), ('USD', 'USD'), ('UAK', 'UAK'), ('ARM', 'ARM'), ('PYG', 'PYG'), ('XRE', 'XRE'), ('ESA', 'ESA'), ('GMD', 'GMD'), ('SBD', 'SBD'), ('VNN', 'VNN'), ('BGN', 'BGN'), ('GHS', 'GHS'), ('XPD', 'XPD'), ('BRZ', 'BRZ'), ('BYB', 'BYB'), ('NZD', 'NZD'), ('SDD', 'SDD'), ('VEB', 'VEB'), ('ROL', 'ROL'), ('MOP', 'MOP'), ('BSD', 'BSD'), ('BIF', 'BIF'), ('HUF', 'HUF'), ('GEL', 'GEL'), ('PTE', 'PTE'), ('LVL', 'LVL'), ('TWD', 'TWD'), ('TJR', 'TJR'), ('BOB', 'BOB'), ('FKP', 'FKP'), ('HRD', 'HRD'), ('CUP', 'CUP'), ('BHD', 'BHD'), ('ADP', 'ADP'), ('ZMK', 'ZMK'), ('XSU', 'XSU'), ('XXX', 'XXX'), ('XBC', 'XBC'), ('SSP', 'SSP'), ('AZM', 'AZM'), ('BYN', 'BYN'), ('IQD', 'IQD'), ('STD', 'STD'), ('SCR', 'SCR'), ('MZM', 'MZM'), ('HKD', 'HKD'), ('YUR', 'YUR'), ('GEK', 'GEK'), ('HRK', 'HRK'), ('CHW', 'CHW'), ('RON', 'RON'), ('BND', 'BND'), ('MZE', 'MZE'), ('SGD', 'SGD'), ('XCD', 'XCD'), ('IEP', 'IEP'), ('GNF', 'GNF'), ('CNX', 'CNX'), ('CZK', 'CZK'), ('ARL', 'ARL'), ('DDM', 'DDM'), ('DKK', 'DKK'), ('MKN', 'MKN'), ('BRE', 'BRE'), ('PES', 'PES'), ('SRD', 'SRD'), ('BRC', 'BRC'), ('COU', 'COU'), ('ZAL', 'ZAL'), ('ITL', 'ITL'), ('KMF', 'KMF'), ('CLE', 'CLE'), ('JOD', 'JOD'), ('HTG', 'HTG'), ('TZS', 'TZS'), ('SDG', 'SDG'), ('SOS', 'SOS'), ('XPF', 'XPF'), ('PEN', 'PEN'), ('MLF', 'MLF'), ('TOP', 'TOP')], max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
