# Generated by Django 3.1.4 on 2021-01-13 16:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('short_description', models.CharField(blank=True, max_length=800, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('unit', models.CharField(choices=[('dozen', 'Dozen'), ('mg', 'MG'), ('g', 'G'), ('lb', 'Pound(lb)'), ('kg', 'KG'), ('mm', 'MM'), ('m', 'M'), ('inch', 'Inch'), ('ft', 'FT'), ('ml', 'ML'), ('l', 'L'), ('item', 'Item')], max_length=300)),
                ('avg_price', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('GHS', 'GHS'), ('LKR', 'LKR'), ('LUC', 'LUC'), ('MCF', 'MCF'), ('USN', 'USN'), ('SUR', 'SUR'), ('YUR', 'YUR'), ('GEK', 'GEK'), ('MVR', 'MVR'), ('CDF', 'CDF'), ('TPE', 'TPE'), ('ROL', 'ROL'), ('BND', 'BND'), ('MZN', 'MZN'), ('SLL', 'SLL'), ('ZRN', 'ZRN'), ('MXV', 'MXV'), ('NOK', 'NOK'), ('ALL', 'ALL'), ('AZM', 'AZM'), ('ERN', 'ERN'), ('ESP', 'ESP'), ('KRO', 'KRO'), ('XUA', 'XUA'), ('ETB', 'ETB'), ('GWE', 'GWE'), ('SRG', 'SRG'), ('ZWD', 'ZWD'), ('COU', 'COU'), ('TND', 'TND'), ('UGS', 'UGS'), ('AOA', 'AOA'), ('MUR', 'MUR'), ('YUN', 'YUN'), ('BOB', 'BOB'), ('RSD', 'RSD'), ('MVP', 'MVP'), ('KHR', 'KHR'), ('GIP', 'GIP'), ('BAM', 'BAM'), ('FRF', 'FRF'), ('AWG', 'AWG'), ('MRU', 'MRU'), ('JMD', 'JMD'), ('BAD', 'BAD'), ('KZT', 'KZT'), ('CSK', 'CSK'), ('BIF', 'BIF'), ('SBD', 'SBD'), ('TRY', 'TRY'), ('XAG', 'XAG'), ('DEM', 'DEM'), ('TJS', 'TJS'), ('KYD', 'KYD'), ('KRH', 'KRH'), ('VUV', 'VUV'), ('HRD', 'HRD'), ('IRR', 'IRR'), ('VNN', 'VNN'), ('MTL', 'MTL'), ('PES', 'PES'), ('XTS', 'XTS'), ('ECS', 'ECS'), ('NIO', 'NIO'), ('EEK', 'EEK'), ('SSP', 'SSP'), ('XSU', 'XSU'), ('SCR', 'SCR'), ('XOF', 'XOF'), ('RWF', 'RWF'), ('CVE', 'CVE'), ('MXP', 'MXP'), ('AFA', 'AFA'), ('CNH', 'CNH'), ('KES', 'KES'), ('GWP', 'GWP'), ('BRC', 'BRC'), ('SVC', 'SVC'), ('BZD', 'BZD'), ('AED', 'AED'), ('ARM', 'ARM'), ('UAH', 'UAH'), ('CRC', 'CRC'), ('YER', 'YER'), ('BRE', 'BRE'), ('DDM', 'DDM'), ('ISK', 'ISK'), ('PLN', 'PLN'), ('XPT', 'XPT'), ('PEI', 'PEI'), ('PGK', 'PGK'), ('HTG', 'HTG'), ('LBP', 'LBP'), ('TMM', 'TMM'), ('BYR', 'BYR'), ('XBD', 'XBD'), ('IEP', 'IEP'), ('LTL', 'LTL'), ('TMT', 'TMT'), ('XBB', 'XBB'), ('NAD', 'NAD'), ('UAK', 'UAK'), ('EGP', 'EGP'), ('THB', 'THB'), ('BGN', 'BGN'), ('BDT', 'BDT'), ('USS', 'USS'), ('NPR', 'NPR'), ('MKD', 'MKD'), ('HKD', 'HKD'), ('KMF', 'KMF'), ('YUD', 'YUD'), ('CLF', 'CLF'), ('ILR', 'ILR'), ('CHE', 'CHE'), ('LAK', 'LAK'), ('ZWR', 'ZWR'), ('GTQ', 'GTQ'), ('SHP', 'SHP'), ('GYD', 'GYD'), ('RHD', 'RHD'), ('DOP', 'DOP'), ('KGS', 'KGS'), ('BYB', 'BYB'), ('ZRZ', 'ZRZ'), ('IQD', 'IQD'), ('LUL', 'LUL'), ('XRE', 'XRE'), ('CSD', 'CSD'), ('BGM', 'BGM'), ('ILS', 'ILS'), ('LUF', 'LUF'), ('BOL', 'BOL'), ('BUK', 'BUK'), ('YDD', 'YDD'), ('PHP', 'PHP'), ('SGD', 'SGD'), ('BHD', 'BHD'), ('BMD', 'BMD'), ('BWP', 'BWP'), ('XPF', 'XPF'), ('SDP', 'SDP'), ('MXN', 'MXN'), ('BOP', 'BOP'), ('NLG', 'NLG'), ('PKR', 'PKR'), ('BEL', 'BEL'), ('VEB', 'VEB'), ('XAU', 'XAU'), ('MGF', 'MGF'), ('RON', 'RON'), ('ARP', 'ARP'), ('VES', 'VES'), ('GQE', 'GQE'), ('USD', 'USD'), ('SEK', 'SEK'), ('COP', 'COP'), ('GEL', 'GEL'), ('MLF', 'MLF'), ('BSD', 'BSD'), ('BRL', 'BRL'), ('UYI', 'UYI'), ('UYU', 'UYU'), ('RUB', 'RUB'), ('AZN', 'AZN'), ('TJR', 'TJR'), ('KWD', 'KWD'), ('BGL', 'BGL'), ('STN', 'STN'), ('SYP', 'SYP'), ('UYP', 'UYP'), ('AOK', 'AOK'), ('GRD', 'GRD'), ('UGX', 'UGX'), ('PTE', 'PTE'), ('GNS', 'GNS'), ('BRB', 'BRB'), ('NGN', 'NGN'), ('GNF', 'GNF'), ('VND', 'VND'), ('UZS', 'UZS'), ('SDD', 'SDD'), ('ZAR', 'ZAR'), ('NIC', 'NIC'), ('BGO', 'BGO'), ('BEF', 'BEF'), ('LVR', 'LVR'), ('BTN', 'BTN'), ('AOR', 'AOR'), ('CUP', 'CUP'), ('BAN', 'BAN'), ('LTT', 'LTT'), ('BRN', 'BRN'), ('DZD', 'DZD'), ('ANG', 'ANG'), ('XDR', 'XDR'), ('MDL', 'MDL'), ('MWK', 'MWK'), ('CNY', 'CNY'), ('CNX', 'CNX'), ('ESB', 'ESB'), ('MNT', 'MNT'), ('WST', 'WST'), ('XCD', 'XCD'), ('ISJ', 'ISJ'), ('XAF', 'XAF'), ('TWD', 'TWD'), ('DJF', 'DJF'), ('GMD', 'GMD'), ('KRW', 'KRW'), ('QAR', 'QAR'), ('AUD', 'AUD'), ('PEN', 'PEN'), ('AON', 'AON'), ('MAD', 'MAD'), ('ECV', 'ECV'), ('MTP', 'MTP'), ('CZK', 'CZK'), ('HRK', 'HRK'), ('MOP', 'MOP'), ('TOP', 'TOP'), ('LVL', 'LVL'), ('MZM', 'MZM'), ('ARS', 'ARS'), ('SRD', 'SRD'), ('BBD', 'BBD'), ('MAF', 'MAF'), ('SZL', 'SZL'), ('XFU', 'XFU'), ('MRO', 'MRO'), ('ATS', 'ATS'), ('ALK', 'ALK'), ('CLP', 'CLP'), ('PLZ', 'PLZ'), ('ZWL', 'ZWL'), ('ITL', 'ITL'), ('XPD', 'XPD'), ('MMK', 'MMK'), ('RUR', 'RUR'), ('AMD', 'AMD'), ('SIT', 'SIT'), ('ADP', 'ADP'), ('GHC', 'GHC'), ('ZMW', 'ZMW'), ('HNL', 'HNL'), ('OMR', 'OMR'), ('FJD', 'FJD'), ('ZMK', 'ZMK'), ('CHF', 'CHF'), ('BEC', 'BEC'), ('XXX', 'XXX'), ('INR', 'INR'), ('AFN', 'AFN'), ('MGA', 'MGA'), ('ARA', 'ARA'), ('TTD', 'TTD'), ('HUF', 'HUF'), ('TRL', 'TRL'), ('CAD', 'CAD'), ('ILP', 'ILP'), ('ESA', 'ESA'), ('LYD', 'LYD'), ('JPY', 'JPY'), ('NZD', 'NZD'), ('GBP', 'GBP'), ('LRD', 'LRD'), ('TZS', 'TZS'), ('SDG', 'SDG'), ('KPW', 'KPW'), ('PYG', 'PYG'), ('XBA', 'XBA'), ('IDR', 'IDR'), ('YUM', 'YUM'), ('FKP', 'FKP'), ('CYP', 'CYP'), ('BRR', 'BRR'), ('BRZ', 'BRZ'), ('CLE', 'CLE'), ('CHW', 'CHW'), ('MZE', 'MZE'), ('FIM', 'FIM'), ('XEU', 'XEU'), ('DKK', 'DKK'), ('SAR', 'SAR'), ('JOD', 'JOD'), ('ARL', 'ARL'), ('EUR', 'EUR'), ('SKK', 'SKK'), ('MKN', 'MKN'), ('PAB', 'PAB'), ('BYN', 'BYN'), ('UYW', 'UYW'), ('STD', 'STD'), ('CUC', 'CUC'), ('XBC', 'XBC'), ('SOS', 'SOS'), ('MDC', 'MDC'), ('ZAL', 'ZAL'), ('XFO', 'XFO'), ('MYR', 'MYR'), ('BOV', 'BOV'), ('LSL', 'LSL'), ('VEF', 'VEF')], max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
