# Generated by Django 3.1.5 on 2021-01-27 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('short_description', models.CharField(blank=True, max_length=800, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('unit', models.CharField(choices=[('dozen', 'Dozen'), ('mg', 'MG'), ('g', 'G'), ('lb', 'Pound(lb)'), ('kg', 'KG'), ('mm', 'MM'), ('m', 'M'), ('inch', 'Inch'), ('ft', 'FT'), ('ml', 'ML'), ('l', 'L'), ('item', 'Item'), ('box', 'Box')], max_length=300)),
                ('avg_price', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('AZM', 'AZM'), ('KRO', 'KRO'), ('MLF', 'MLF'), ('XBD', 'XBD'), ('BRR', 'BRR'), ('XBC', 'XBC'), ('CHF', 'CHF'), ('SDG', 'SDG'), ('PTE', 'PTE'), ('SRG', 'SRG'), ('ROL', 'ROL'), ('MYR', 'MYR'), ('UZS', 'UZS'), ('STD', 'STD'), ('TJS', 'TJS'), ('INR', 'INR'), ('BHD', 'BHD'), ('MRU', 'MRU'), ('TMM', 'TMM'), ('USN', 'USN'), ('MOP', 'MOP'), ('MXN', 'MXN'), ('ZRZ', 'ZRZ'), ('ILS', 'ILS'), ('BSD', 'BSD'), ('PAB', 'PAB'), ('ESB', 'ESB'), ('SDP', 'SDP'), ('ECV', 'ECV'), ('LUF', 'LUF'), ('BRE', 'BRE'), ('SIT', 'SIT'), ('PGK', 'PGK'), ('AUD', 'AUD'), ('CNH', 'CNH'), ('MZN', 'MZN'), ('DKK', 'DKK'), ('MAD', 'MAD'), ('XDR', 'XDR'), ('JPY', 'JPY'), ('SUR', 'SUR'), ('TND', 'TND'), ('BOL', 'BOL'), ('QAR', 'QAR'), ('NOK', 'NOK'), ('MTL', 'MTL'), ('CSD', 'CSD'), ('AZN', 'AZN'), ('NPR', 'NPR'), ('ZAL', 'ZAL'), ('MDL', 'MDL'), ('ERN', 'ERN'), ('IQD', 'IQD'), ('ILR', 'ILR'), ('RWF', 'RWF'), ('CYP', 'CYP'), ('TZS', 'TZS'), ('ALL', 'ALL'), ('ATS', 'ATS'), ('BGL', 'BGL'), ('TRY', 'TRY'), ('BGM', 'BGM'), ('SAR', 'SAR'), ('GYD', 'GYD'), ('UYP', 'UYP'), ('AOR', 'AOR'), ('MRO', 'MRO'), ('XOF', 'XOF'), ('FJD', 'FJD'), ('AOA', 'AOA'), ('BAM', 'BAM'), ('XPD', 'XPD'), ('LUL', 'LUL'), ('YER', 'YER'), ('EEK', 'EEK'), ('PKR', 'PKR'), ('YUM', 'YUM'), ('DEM', 'DEM'), ('BIF', 'BIF'), ('ETB', 'ETB'), ('EUR', 'EUR'), ('SSP', 'SSP'), ('BRZ', 'BRZ'), ('MDC', 'MDC'), ('HUF', 'HUF'), ('TMT', 'TMT'), ('NZD', 'NZD'), ('BZD', 'BZD'), ('DZD', 'DZD'), ('VNN', 'VNN'), ('ARM', 'ARM'), ('XCD', 'XCD'), ('GEL', 'GEL'), ('NIO', 'NIO'), ('MVR', 'MVR'), ('SRD', 'SRD'), ('IEP', 'IEP'), ('ZWL', 'ZWL'), ('MNT', 'MNT'), ('GQE', 'GQE'), ('LYD', 'LYD'), ('LKR', 'LKR'), ('SYP', 'SYP'), ('MCF', 'MCF'), ('XXX', 'XXX'), ('IRR', 'IRR'), ('MAF', 'MAF'), ('BYR', 'BYR'), ('CLP', 'CLP'), ('GTQ', 'GTQ'), ('BEL', 'BEL'), ('XTS', 'XTS'), ('XPT', 'XPT'), ('UYW', 'UYW'), ('XAF', 'XAF'), ('BRC', 'BRC'), ('VEF', 'VEF'), ('GBP', 'GBP'), ('KGS', 'KGS'), ('GRD', 'GRD'), ('BOB', 'BOB'), ('PES', 'PES'), ('STN', 'STN'), ('JMD', 'JMD'), ('LRD', 'LRD'), ('XFO', 'XFO'), ('MGF', 'MGF'), ('HRD', 'HRD'), ('BEC', 'BEC'), ('CDF', 'CDF'), ('TTD', 'TTD'), ('ALK', 'ALK'), ('RUR', 'RUR'), ('GWP', 'GWP'), ('KRH', 'KRH'), ('BOV', 'BOV'), ('THB', 'THB'), ('NIC', 'NIC'), ('BTN', 'BTN'), ('JOD', 'JOD'), ('MGA', 'MGA'), ('CNY', 'CNY'), ('UGS', 'UGS'), ('ZMK', 'ZMK'), ('BYB', 'BYB'), ('FRF', 'FRF'), ('USS', 'USS'), ('UYI', 'UYI'), ('MZE', 'MZE'), ('PEI', 'PEI'), ('YDD', 'YDD'), ('ISK', 'ISK'), ('HNL', 'HNL'), ('AMD', 'AMD'), ('MZM', 'MZM'), ('RUB', 'RUB'), ('MMK', 'MMK'), ('BRN', 'BRN'), ('GEK', 'GEK'), ('LTL', 'LTL'), ('ISJ', 'ISJ'), ('XFU', 'XFU'), ('XRE', 'XRE'), ('GWE', 'GWE'), ('BGN', 'BGN'), ('COU', 'COU'), ('DDM', 'DDM'), ('ARP', 'ARP'), ('HTG', 'HTG'), ('DJF', 'DJF'), ('NAD', 'NAD'), ('USD', 'USD'), ('BAN', 'BAN'), ('XPF', 'XPF'), ('BND', 'BND'), ('DOP', 'DOP'), ('ILP', 'ILP'), ('LBP', 'LBP'), ('LVL', 'LVL'), ('YUD', 'YUD'), ('EGP', 'EGP'), ('UYU', 'UYU'), ('BUK', 'BUK'), ('KZT', 'KZT'), ('UAH', 'UAH'), ('SVC', 'SVC'), ('YUR', 'YUR'), ('XEU', 'XEU'), ('AFA', 'AFA'), ('CUP', 'CUP'), ('MVP', 'MVP'), ('XBA', 'XBA'), ('LAK', 'LAK'), ('NGN', 'NGN'), ('COP', 'COP'), ('XUA', 'XUA'), ('ANG', 'ANG'), ('SZL', 'SZL'), ('PYG', 'PYG'), ('CZK', 'CZK'), ('ESA', 'ESA'), ('MXV', 'MXV'), ('CNX', 'CNX'), ('SCR', 'SCR'), ('MXP', 'MXP'), ('ZMW', 'ZMW'), ('NLG', 'NLG'), ('VND', 'VND'), ('GNF', 'GNF'), ('ZWD', 'ZWD'), ('GNS', 'GNS'), ('BDT', 'BDT'), ('SBD', 'SBD'), ('VUV', 'VUV'), ('AWG', 'AWG'), ('BYN', 'BYN'), ('TRL', 'TRL'), ('LVR', 'LVR'), ('CHW', 'CHW'), ('BOP', 'BOP'), ('PLN', 'PLN'), ('VEB', 'VEB'), ('CLE', 'CLE'), ('GHC', 'GHC'), ('ESP', 'ESP'), ('KPW', 'KPW'), ('MUR', 'MUR'), ('LUC', 'LUC'), ('ZAR', 'ZAR'), ('WST', 'WST'), ('KYD', 'KYD'), ('BMD', 'BMD'), ('MTP', 'MTP'), ('OMR', 'OMR'), ('TJR', 'TJR'), ('XAG', 'XAG'), ('BRB', 'BRB'), ('ZRN', 'ZRN'), ('CUC', 'CUC'), ('CSK', 'CSK'), ('GMD', 'GMD'), ('KRW', 'KRW'), ('SKK', 'SKK'), ('TOP', 'TOP'), ('FIM', 'FIM'), ('GIP', 'GIP'), ('FKP', 'FKP'), ('BRL', 'BRL'), ('ZWR', 'ZWR'), ('CRC', 'CRC'), ('AON', 'AON'), ('AED', 'AED'), ('BEF', 'BEF'), ('MKD', 'MKD'), ('MKN', 'MKN'), ('ECS', 'ECS'), ('UGX', 'UGX'), ('SGD', 'SGD'), ('SLL', 'SLL'), ('ARL', 'ARL'), ('LSL', 'LSL'), ('XBB', 'XBB'), ('KHR', 'KHR'), ('BWP', 'BWP'), ('BGO', 'BGO'), ('CVE', 'CVE'), ('LTT', 'LTT'), ('ITL', 'ITL'), ('KWD', 'KWD'), ('ARA', 'ARA'), ('VES', 'VES'), ('AOK', 'AOK'), ('YUN', 'YUN'), ('SOS', 'SOS'), ('XSU', 'XSU'), ('PLZ', 'PLZ'), ('SEK', 'SEK'), ('BBD', 'BBD'), ('AFN', 'AFN'), ('TWD', 'TWD'), ('MWK', 'MWK'), ('SHP', 'SHP'), ('CAD', 'CAD'), ('RSD', 'RSD'), ('HRK', 'HRK'), ('XAU', 'XAU'), ('ADP', 'ADP'), ('HKD', 'HKD'), ('BAD', 'BAD'), ('CLF', 'CLF'), ('CHE', 'CHE'), ('KES', 'KES'), ('KMF', 'KMF'), ('TPE', 'TPE'), ('PEN', 'PEN'), ('GHS', 'GHS'), ('PHP', 'PHP'), ('SDD', 'SDD'), ('RHD', 'RHD'), ('ARS', 'ARS'), ('UAK', 'UAK'), ('IDR', 'IDR'), ('RON', 'RON')], max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
