# Generated by Django 3.1.4 on 2021-01-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_auto_20210107_1105'),
        ('products', '0006_auto_20210107_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('PYG', 'PYG'), ('SDD', 'SDD'), ('EGP', 'EGP'), ('AZN', 'AZN'), ('MWK', 'MWK'), ('CSK', 'CSK'), ('MCF', 'MCF'), ('STN', 'STN'), ('UYW', 'UYW'), ('ARM', 'ARM'), ('MDC', 'MDC'), ('ZAL', 'ZAL'), ('NZD', 'NZD'), ('AOK', 'AOK'), ('KRH', 'KRH'), ('SVC', 'SVC'), ('LVL', 'LVL'), ('ECS', 'ECS'), ('XBC', 'XBC'), ('SGD', 'SGD'), ('AON', 'AON'), ('LAK', 'LAK'), ('XAU', 'XAU'), ('XEU', 'XEU'), ('NIO', 'NIO'), ('XRE', 'XRE'), ('HRD', 'HRD'), ('BUK', 'BUK'), ('MMK', 'MMK'), ('NGN', 'NGN'), ('YER', 'YER'), ('SLL', 'SLL'), ('XPF', 'XPF'), ('XPD', 'XPD'), ('JOD', 'JOD'), ('SRD', 'SRD'), ('THB', 'THB'), ('XCD', 'XCD'), ('BRN', 'BRN'), ('BSD', 'BSD'), ('SRG', 'SRG'), ('FJD', 'FJD'), ('PLZ', 'PLZ'), ('MZE', 'MZE'), ('KPW', 'KPW'), ('CNY', 'CNY'), ('RWF', 'RWF'), ('PES', 'PES'), ('CHF', 'CHF'), ('BGM', 'BGM'), ('XSU', 'XSU'), ('KMF', 'KMF'), ('SOS', 'SOS'), ('GHC', 'GHC'), ('SBD', 'SBD'), ('RHD', 'RHD'), ('ARS', 'ARS'), ('MZM', 'MZM'), ('SHP', 'SHP'), ('BRL', 'BRL'), ('UGX', 'UGX'), ('XOF', 'XOF'), ('IDR', 'IDR'), ('CDF', 'CDF'), ('ITL', 'ITL'), ('DDM', 'DDM'), ('BEC', 'BEC'), ('BOV', 'BOV'), ('GHS', 'GHS'), ('XPT', 'XPT'), ('LUC', 'LUC'), ('XAF', 'XAF'), ('PAB', 'PAB'), ('XUA', 'XUA'), ('GMD', 'GMD'), ('ILP', 'ILP'), ('BMD', 'BMD'), ('BEF', 'BEF'), ('HUF', 'HUF'), ('LRD', 'LRD'), ('MTP', 'MTP'), ('UYP', 'UYP'), ('BRB', 'BRB'), ('INR', 'INR'), ('TJR', 'TJR'), ('CVE', 'CVE'), ('ISK', 'ISK'), ('AED', 'AED'), ('ILS', 'ILS'), ('ESP', 'ESP'), ('BOL', 'BOL'), ('CNX', 'CNX'), ('COU', 'COU'), ('KRO', 'KRO'), ('KES', 'KES'), ('TTD', 'TTD'), ('GEL', 'GEL'), ('ILR', 'ILR'), ('VNN', 'VNN'), ('ARL', 'ARL'), ('MZN', 'MZN'), ('SAR', 'SAR'), ('SCR', 'SCR'), ('YUR', 'YUR'), ('MXV', 'MXV'), ('USN', 'USN'), ('ZWL', 'ZWL'), ('BYB', 'BYB'), ('UYI', 'UYI'), ('TRL', 'TRL'), ('ANG', 'ANG'), ('SDP', 'SDP'), ('ZMW', 'ZMW'), ('BRR', 'BRR'), ('ESA', 'ESA'), ('XTS', 'XTS'), ('LSL', 'LSL'), ('MDL', 'MDL'), ('DKK', 'DKK'), ('BOP', 'BOP'), ('DEM', 'DEM'), ('MKD', 'MKD'), ('CNH', 'CNH'), ('PEI', 'PEI'), ('YDD', 'YDD'), ('MOP', 'MOP'), ('TPE', 'TPE'), ('AFA', 'AFA'), ('LTT', 'LTT'), ('BIF', 'BIF'), ('TND', 'TND'), ('BBD', 'BBD'), ('MAF', 'MAF'), ('BGO', 'BGO'), ('NOK', 'NOK'), ('JMD', 'JMD'), ('LTL', 'LTL'), ('MRO', 'MRO'), ('ALL', 'ALL'), ('LVR', 'LVR'), ('MGA', 'MGA'), ('CLP', 'CLP'), ('GIP', 'GIP'), ('PGK', 'PGK'), ('PTE', 'PTE'), ('SDG', 'SDG'), ('FRF', 'FRF'), ('GBP', 'GBP'), ('AWG', 'AWG'), ('JPY', 'JPY'), ('HNL', 'HNL'), ('YUN', 'YUN'), ('STD', 'STD'), ('CHE', 'CHE'), ('PEN', 'PEN'), ('MVR', 'MVR'), ('LKR', 'LKR'), ('YUD', 'YUD'), ('BAM', 'BAM'), ('MAD', 'MAD'), ('SYP', 'SYP'), ('EUR', 'EUR'), ('UAK', 'UAK'), ('ISJ', 'ISJ'), ('ETB', 'ETB'), ('BAN', 'BAN'), ('MTL', 'MTL'), ('CAD', 'CAD'), ('EEK', 'EEK'), ('SIT', 'SIT'), ('NPR', 'NPR'), ('XFU', 'XFU'), ('COP', 'COP'), ('GNF', 'GNF'), ('GQE', 'GQE'), ('XXX', 'XXX'), ('CYP', 'CYP'), ('MGF', 'MGF'), ('WST', 'WST'), ('GWE', 'GWE'), ('RUR', 'RUR'), ('AMD', 'AMD'), ('USD', 'USD'), ('UZS', 'UZS'), ('XBB', 'XBB'), ('USS', 'USS'), ('NLG', 'NLG'), ('BEL', 'BEL'), ('BYR', 'BYR'), ('TZS', 'TZS'), ('TMM', 'TMM'), ('CHW', 'CHW'), ('DOP', 'DOP'), ('SKK', 'SKK'), ('YUM', 'YUM'), ('MLF', 'MLF'), ('IEP', 'IEP'), ('BTN', 'BTN'), ('SZL', 'SZL'), ('GRD', 'GRD'), ('LBP', 'LBP'), ('IQD', 'IQD'), ('CLF', 'CLF'), ('MKN', 'MKN'), ('AZM', 'AZM'), ('VEB', 'VEB'), ('CRC', 'CRC'), ('UYU', 'UYU'), ('DJF', 'DJF'), ('BYN', 'BYN'), ('ZMK', 'ZMK'), ('TJS', 'TJS'), ('OMR', 'OMR'), ('AOR', 'AOR'), ('RON', 'RON'), ('KRW', 'KRW'), ('MXP', 'MXP'), ('BDT', 'BDT'), ('FIM', 'FIM'), ('AFN', 'AFN'), ('LUF', 'LUF'), ('UGS', 'UGS'), ('ARP', 'ARP'), ('KHR', 'KHR'), ('SEK', 'SEK'), ('ERN', 'ERN'), ('FKP', 'FKP'), ('BRC', 'BRC'), ('TMT', 'TMT'), ('NIC', 'NIC'), ('LYD', 'LYD'), ('CLE', 'CLE'), ('QAR', 'QAR'), ('SUR', 'SUR'), ('PHP', 'PHP'), ('BRE', 'BRE'), ('ADP', 'ADP'), ('XBA', 'XBA'), ('TRY', 'TRY'), ('ALK', 'ALK'), ('BND', 'BND'), ('MVP', 'MVP'), ('HRK', 'HRK'), ('VND', 'VND'), ('TOP', 'TOP'), ('AUD', 'AUD'), ('MNT', 'MNT'), ('ARA', 'ARA'), ('ECV', 'ECV'), ('VEF', 'VEF'), ('XDR', 'XDR'), ('CSD', 'CSD'), ('GEK', 'GEK'), ('MXN', 'MXN'), ('IRR', 'IRR'), ('KZT', 'KZT'), ('ZRN', 'ZRN'), ('ATS', 'ATS'), ('CUP', 'CUP'), ('UAH', 'UAH'), ('NAD', 'NAD'), ('GTQ', 'GTQ'), ('XBD', 'XBD'), ('BHD', 'BHD'), ('ZWD', 'ZWD'), ('XAG', 'XAG'), ('XFO', 'XFO'), ('BWP', 'BWP'), ('HTG', 'HTG'), ('MYR', 'MYR'), ('HKD', 'HKD'), ('BRZ', 'BRZ'), ('RUB', 'RUB'), ('SSP', 'SSP'), ('BZD', 'BZD'), ('VES', 'VES'), ('BGL', 'BGL'), ('RSD', 'RSD'), ('CUC', 'CUC'), ('KYD', 'KYD'), ('ROL', 'ROL'), ('ZWR', 'ZWR'), ('GNS', 'GNS'), ('MUR', 'MUR'), ('PKR', 'PKR'), ('VUV', 'VUV'), ('CZK', 'CZK'), ('ESB', 'ESB'), ('AOA', 'AOA'), ('LUL', 'LUL'), ('KGS', 'KGS'), ('TWD', 'TWD'), ('MRU', 'MRU'), ('GYD', 'GYD'), ('ZRZ', 'ZRZ'), ('DZD', 'DZD'), ('BAD', 'BAD'), ('BOB', 'BOB'), ('GWP', 'GWP'), ('KWD', 'KWD'), ('ZAR', 'ZAR'), ('PLN', 'PLN'), ('BGN', 'BGN')], max_length=100),
        ),
    ]
