# Generated by Django 3.1.5 on 2021-01-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210119_0634'),
        ('products', '0013_auto_20210118_0659'),
    ]

    operations = [
    ]
